bifrost:
  # Override the default path to the one used in the docker image
  cert_file: "certs/cert.pem"
  hass_ui_file: "hass-ui.yaml"
  hass_runtime_file: "hass-runtime.yaml"

bridge:
  name: Bifrost
  mac: 00:11:22:33:44:55
  ipaddress: 10.12.0.20
  netmask: 255.255.255.0
  gateway: 10.12.0.1
  timezone: Europe/Copenhagen

z2m:
  server1:
    url: ws://10.0.0.100:8080

hass:
  homeassistant:
    url: http://192.168.2.5:8123
    token_env: HASS_TOKEN
